---
abstract: 'Executable Uniform Command-Line Interface Descriptions'
author:
  - 'Damian Conway <DCONWAY@cpan.org>'
build_requires:
  Pod::Checker: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Getopt-Euclid
provides:
  Getopt::Euclid:
    file: lib/Getopt/Euclid.pm
    version: v0.4.3
recommends:
  IO::Pager::Page: 0
requires:
  File::Basename: 0
  File::Spec::Functions: 0
  List::Util: 0
  Pod::PlainText: 0
  Pod::Select: 0
  Text::Balanced: 0
  version: 0
resources:
  license: http://dev.perl.org/licenses/
version: v0.4.3
