---
abstract: 'Executable Uniform Command-Line Interface Descriptions'
author:
  - 'Damian Conway <DCONWAY@cpan.org>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Getopt-Euclid
provides:
  Getopt::Euclid:
    file: lib/Getopt/Euclid.pm
    version: v0.2.2
  Getopt::Euclid::HierDemo:
    file: lib/Getopt/Euclid/HierDemo.pm
requires:
  File::Spec::Functions: 0
  List::Util: 0
  Test::More: 0
  version: 0
resources:
  license: http://dev.perl.org/licenses/
version: v0.2.2
