# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Getopt-Euclid
version:      v0.1.0
version_from: lib/Getopt/Euclid.pm
installdirs:  site
requires:
    File::Spec::Functions:         0
    List::Util:                    0
    Test::More:                    0
    version:                       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
