---
abstract: 'Executable Uniform Command-Line Interface Descriptions'
author:
  - 'Damian Conway (DCONWAY@CPAN.org)'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Pod::Checker: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Getopt-Euclid
no_index:
  directory:
    - inc
    - t
recommends:
  IO::Pager::Page: 0
requires:
  File::Basename: 0
  File::Spec::Functions: 0
  List::Util: 0
  Pod::PlainText: 0
  Pod::Select: 0
  Text::Balanced: 0
  perl: 5.005
  version: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Getopt-Euclid
  homepage: http://search.cpan.org/search?query=Getopt%3A%3AEuclid&mode=dist
  license: http://dev.perl.org/licenses/
  repository: git://getopt-euclid.git.sourceforge.net/gitroot/getopt-euclid/getopt-euclid
version: 0.004002
